version: '3'
services:
  nginx:
#    image: nginx:latest
    build: ./nginx
#    container_name: nginx
#    hostname: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
#    container_name: php
#    hostname: php
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.4.21
#    container_name: mariadb
#    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306
    volumes:
      - ./db/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
