services:
  app:
    image: eclipse-temurin:17
    ports:
      - 8080:8080
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    tty: true

  db:
    build: ./mysql
    volumes:
      - .db-store:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db-store:
