services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on: 
      - php
  php:
    build: ./php
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    volumes:
      - ./app:/var/www/html
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 33306:3306
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    depends_on:
      - mysql
networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
